### ISSUE TITLE
[Launch dialog] Distinguish same launch config names among different projects

### ISSUE THREAD

**Issue by diskostu** [rherrmann/eclipse-extras#34]
Sometimes you have launch configs with the same name among different projects, e.g. a trunk- and a branch-project. Within the launch dialog, we cannot distinguish between them yet.

**Comment by rherrmann** [comment]
Not sure if I undertand correctly, do you have launch configs with the same at the same time and both are listed in the launch dialog?

**Comment by diskostu** [comment]
Yep.
![2016-02-11 16_48_54-start launch configuration](https://cloud.githubusercontent.com/assets/574147/12981084/79df67e8-d0df-11e5-9614-2baccd840e93.png)

**Comment by rherrmann** [comment]
Launch config names should be unique within the workspace. Attempting to create two alunch configs with the same name in the launch config dialog is not possible.

How did you manage to create the launch cofigs? Don't you get validation errors when editing them in the launch config dialog?

Note, I could decorate the names with the project they are stored in (if any) without too much effort, but I would like to know the conditions that led to duplicate names first.

**Comment by diskostu** [comment]
There is a validation within the Eclipse launch config dialog; you cannot
create a launch config with the same name as an existing one.

But, if you import or check out a project which contains launch configs
with names like existing ones, it's perfectly fine for Eclipse.
Am 11.02.2016 17:09 schrieb "Rüdiger Herrmann" notifications@github.com:

**Comment by rherrmann** [comment]
Thanks for the clarification.

Then I will decorate duplicate enties with their containing project. Something like:

```
foo - Web Application (project1)
foo - Web Application (project2)
```

**Comment by rherrmann** [comment]
Fixed with commit ec178685314fd2eb85ea629fa78b6870a419ad96. Duplicate entries will now be shown as `launch config name - storage location` if the launch config is stored in the workspace. The detail label in the status line will always show `launch config name - type (storage location)`.

Thanks a lot for this hint. Please let me know if that solves you problem.

**Comment by diskostu** [comment]
Thanks Rüdiger, that was fast ;) I'll give it a try tomorrow.
Am 11.02.2016 20:07 schrieb "Rüdiger Herrmann" notifications@github.com:

**Comment by diskostu** [comment]
Works like a charm. Thanks a lot!
