### ISSUE TITLE
[New feature] Generate serialVersionUID as a "save action"

### ISSUE THREAD

**Issue by diskostu** [rherrmann/eclipse-extras#36]
Hi there,

I'm thinking of the following use case: I have a class which implements `Serializable` and therefore needs a `serialVersionUID`. Eclipse offers to generate one, everything's fine.

Now, in theory, this field should be updated whenever the class is changed. But this is a manual process and therefore, one tends to forget this step.

Wouldn't it be great if our IDE handles this? For example, everytime I save a class, the IDE generates a new serialVersionUID, for example based on the current timestamp so it is readable. Maybe this could be implemented as a new _save action_?

**Comment by rherrmann** [comment]
I think that changing the `serialVersionUID` with every change isn't the right approach to maintaining a correct serial version.

The serial version should be changed whenever the _serialized version_ of a class changes. This isn't necessarily the case with every change (see the [Java Object Serialization Specification](http://docs.oracle.com/javase/6/docs/platform/serialization/spec/version.html#6678) for more on this). Moreover in many cases backwards comparibility has to be maintained and the serial version stays the same while the serialization implementation is adjusted to seamlessly handle old and new serialized versions.

What I could think of though is a _Save Action_ that adds a `serialVersionUID` if there hasn't been specified one yet. But that is something I would rather see directly implemented in JDT as all the serial version quick fix code is internal to JDT.
