### ISSUE TITLE
Unable to install from marketplace

### ISSUE THREAD

**Issue by fappel** [rherrmann/eclipse-extras#48]
Probably I'm too stupid, but I have not been able to install eclipse-extras from eclipse marketplace. I've tried on two different machines from different networks but the installation process stops on this dialog page:

![image](https://cloud.githubusercontent.com/assets/776277/18027071/8a50d86c-6c59-11e6-80bf-cf8f46f67f13.png)

Note that there is no error log entry. You can hit the confirm button as  often as you wish, the Finish button will not be enabled. Any ideas?

**Comment by rherrmann** [comment]
Thanks for reporting this!
I can reproduce the problem with a fresh _Eclipse for Java Developers 4.6 (Neon)_ installation.

**Comment by rherrmann** [comment]
It seems that this is a marketplace client or p2 installer issue. If you uncheck and check any of the items, the _Finish_ button will be enabled.

Installing the features into _Eclipse for Java Developers 4.5 (Mars)_ works as expected.

**Comment by rherrmann** [comment]
I've filed [bug 500378](https://bugs.eclipse.org/bugs/show_bug.cgi?id=500378), hoping that one of the MPC developers can help resolving this

**Comment by rherrmann** [comment]
All features of Extras for Eclipse used a common _licnese feature_ to avoid maintaining copyright and license inforamtion redundantly.

Commit ab8629fb58e6824474328a2ff4b70cf1a4d539f8 removes the license feature and places the copyright and license information in the respetive features. This workaround solves this issue and the _Finish_ button of the marketplace client wizard is now enabled as expected.

**Comment by rherrmann** [comment]
License features are being back in use again. Commit eb5b113204e6f18fd77eb96a8e74a7ad9f0ad5c7 corrects how features reference the information provided by the license feature and now the marketplace client is also happy.
