### ISSUE TITLE
Provide option to download offline

### ISSUE THREAD

**Issue by rsrini7** [rherrmann/eclipse-extras#62]
In restricted env, github only allowed. It would be good to provide an offline download option as release.

**Comment by rherrmann** [comment]
Fixed with commit 12b4c2a0f718379a4f94bbce42ae7797f0783786.

Please see the Install page for details: https://rherrmann.github.io/eclipse-extras/install

**Comment by rsrini7** [comment]
Thanks. It would be great, if same done for gonsole as well.

**Comment by rherrmann** [comment]
For Gonsole, please open a separate issue in the Gonsole repository. Ideally you could open a pull request. It should be fairly easy to adopt the changes done here for `.travis-deploy.sh`.
